name: Update HTML file in S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: Global
  S3_BUCKET: cicddemoleah
  HTML_FILE: demo.html

jobs:
  update-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

       - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli -y

    - name: Upload HTML file to S3
      run: |
        aws s3 cp ./${{ env.HTML_FILE }} s3://${{ env.S3_BUCKET }}/${{ env.HTML_FILE }}
